### ISSUE TITLE
Windows Photo Viewer cannot load jls files

### ISSUE THREAD

**Issue by lookfeng** [team-charls/jpegls-wic-codec#1]
After register dll, Windows Photo Viewer still load jls files failed.

![error](https://user-images.githubusercontent.com/50478427/57752801-dfdb6d80-771c-11e9-81dd-450da11c0933.png)

**Comment by vbaderks** [comment]
Hi lookfeng,

Thanks for the report.
Can you provide the details of your environment (Windows version, 32\64bit)?

And would it be possible to add the error message as text to this issue, this would make it possible to convert it to English.

**Comment by lookfeng** [comment]
win10 64bit

error msg:
Windows photo viewer can't open this picture because either photo viewer doesn't support this file format, or you don't have the latest updates to photo viewer.

This may be due to errors in the function DllRegisterServer (@dllmain.cpp)

please refer https://github.com/peirick/FlifWICCodec
The FlifWICCodec works well on my computer.

**Comment by vbaderks** [comment]
Thanks for the info. I can reproduce the problem. Will investigate.

**Comment by vbaderks** [comment]
This issue has been closed with commit 54b183f8680985d7e316e5e409651807f200f1fd

If you perform a git pull to the get latest code, rebuild the component and execute regsvr32 jpegls-wic-codec.dll again it should be resolved.
